<a href="https://colab.research.google.com/github/Sh-yadav/Google-Colab-1/blob/master/Numby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

np.ones((2,2), dtype= int)

array([[1, 1],
       [1, 1]])

In [ ]:
a=np.array((3,3))
b=np.reshape(a,(-1,2))
b
b.ndim

2

In [ ]:
a=np.array((3,3))
a.ndim

1

In [ ]:
a=np.zeros((3,3))
a.ndim


2

In [ ]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a=np.zeros((4,1,1))
a

array([[[0.]],

       [[0.]],

       [[0.]],

       [[0.]]])

In [ ]:
np.full(( 2,2), "Hello Python", dtype=None)

array([['Hello Python', 'Hello Python'],
       ['Hello Python', 'Hello Python']], dtype='<U12')

In [ ]:
np.random.rand(5)

array([0.87517673, 0.67938247, 0.4530088 , 0.87501821, 0.01686716])

In [ ]:
data=np.random.randint(5,10,( 10,10) )
data

array([[8, 9, 5, 6, 6, 9, 7, 7, 9, 9],
       [7, 8, 5, 9, 7, 7, 5, 8, 8, 6],
       [7, 9, 7, 9, 5, 6, 7, 9, 8, 5],
       [8, 5, 7, 9, 8, 8, 7, 9, 5, 9],
       [7, 6, 8, 7, 9, 9, 5, 5, 6, 7],
       [9, 7, 7, 9, 8, 8, 7, 7, 6, 5],
       [6, 9, 8, 5, 5, 9, 5, 7, 6, 9],
       [7, 6, 8, 5, 5, 7, 9, 5, 7, 7],
       [9, 7, 8, 5, 8, 5, 9, 5, 9, 7],
       [9, 5, 5, 9, 5, 6, 9, 8, 6, 6]])

In [ ]:
data[1:8]

array([[7, 8, 5, 9, 7, 7, 5, 8, 8, 6],
       [7, 9, 7, 9, 5, 6, 7, 9, 8, 5],
       [8, 5, 7, 9, 8, 8, 7, 9, 5, 9],
       [7, 6, 8, 7, 9, 9, 5, 5, 6, 7],
       [9, 7, 7, 9, 8, 8, 7, 7, 6, 5],
       [6, 9, 8, 5, 5, 9, 5, 7, 6, 9],
       [7, 6, 8, 5, 5, 7, 9, 5, 7, 7]])

In [ ]:
data[1:4,1]

array([8, 9, 5])

In [ ]:
data[1:4,1:5]

array([[8, 5, 9, 7],
       [9, 7, 9, 5],
       [5, 7, 9, 8]])

In [ ]:
data1=np.random.randint(5,15,size=(5,3))

In [ ]:
data1

array([[ 7,  8,  9],
       [12,  5,  5],
       [ 6, 14, 10],
       [ 6, 10, 11],
       [10, 14, 10]])

In [ ]:
data2=np.random.randint(5,15,size=(5,3))
data2

array([[ 5, 12,  9],
       [ 5, 13, 11],
       [ 9, 12,  6],
       [ 9,  8, 11],
       [11,  7,  9]])

In [ ]:
np.hstack([data1,data2] )

array([[10,  5, 12,  5, 12,  9],
       [14,  9, 12,  5, 13, 11],
       [11, 11,  5,  9, 12,  6],
       [ 7, 12, 14,  9,  8, 11],
       [11, 10, 14, 11,  7,  9]])

In [ ]:
np.vstack([data1,data2] )

array([[10,  5, 12],
       [14,  9, 12],
       [11, 11,  5],
       [ 7, 12, 14],
       [11, 10, 14],
       [ 5, 12,  9],
       [ 5, 13, 11],
       [ 9, 12,  6],
       [ 9,  8, 11],
       [11,  7,  9]])

In [ ]:
np.concatenate([data1,data2],axis=1 )

array([[10,  5, 12,  5, 12,  9],
       [14,  9, 12,  5, 13, 11],
       [11, 11,  5,  9, 12,  6],
       [ 7, 12, 14,  9,  8, 11],
       [11, 10, 14, 11,  7,  9]])

In [ ]:
np.random.randint(5,15,size=(5,3,2 ) )

array([[[12, 12],
        [13, 14],
        [ 9,  8]],

       [[10, 12],
        [10,  5],
        [12,  8]],

       [[ 5, 13],
        [14, 11],
        [13,  9]],

       [[ 5, 14],
        [12,  6],
        [ 6,  9]],

       [[ 7,  5],
        [10, 12],
        [13,  7]]])

In [ ]:
data2 = np.random.randint(5,15,size=(5,3,2))
data2

array([[[ 8,  5],
        [ 5,  8],
        [10,  7]],

       [[ 9, 11],
        [11,  8],
        [ 9, 10]],

       [[11, 13],
        [10, 11],
        [ 6, 11]],

       [[11,  6],
        [10, 10],
        [ 8, 12]],

       [[ 9, 10],
        [14,  6],
        [12,  6]]])

In [ ]:
np.concatenate([data1,data2])

ValueError: ignored

splitting data is left
broadcasting

Content

* array of one,zeros,1D,2D


*   reshape of array
full use
random rand
random randint
addition
vstack
hstack



*   List item

